module.exports = {
  GENDER: {
    MALE: "MALE",
    FEMALE: "FEMALE",
  },
  ADMIN_ROLES: {
    SUPER_ADMIN: "SUPER-ADMIN",
    ADMIN: "ADMIN",
    HOSTEL_MANAGER: "HOSTEL-MANAGER",
  },
  USER_TYPE: {
    BUSINESS: "BUSINESS",
    INDIVIDUAL: "INDIVIDUAL",
    USER: "USER",
  },
  TRANSACTION_STATUS: {
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    PENDING: "PENDING",
    CANCELLED: "CANCELLED",
  },
  TRANSACTION_TYPE: {
    CREDIT: "CREDIT",
    DEBIT: "DEBIT",
    WITHDRAWAL: "WITHDRAWAL",
  },
  BOOKING_STATUS: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    CANCELLED: "CANCELLED",
  },
  NOTIFICATION_TYPE: {
    BOOKING_REQUEST: "BOOKING_REQUEST",
    BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
    BOOKING_CANCELLATION: "BOOKING_CANCELLATION",
  },
  PAYMENT_STATUS: {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
  },
  SERVICE_TYPE: {
    FOOD: "FOOD",
    RIDE: "RIDE",
    LAUNDRY: "LAUNDRY"
  },
  EVENT_CATEGORY: {
    MUSIC: "MUSIC",
    PERFORMING_AND_VISUAL_ARTS: "PERFORMING_AND_VISUAL_ARTS",
    HOLIDAY: "HOLIDAY",
    SPORT_AND_FITNESS: "SPORT_AND_FITNESS",
    HEALTH: "HEALTH",
    BUSINESS: "BUSINESS"
  },
  STATUS: {
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    BLOCKED: "BLOCKED"
  },
  CARCondition: {
    WITH_SECURITY: "WITH_SECURITY",
    WITHOUT_SECURITY: "WITHOUT_SECURITY"
  }
};
